#see more ddetails in https://github.com/uken/fluent-plugin-elasticsearch
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-output
data:
  fluentd.conf: |
  
    #configure the logging level to error   
    <system>
      log_level error
    </system>

    # Ignore fluentd own events
    <label @FLUENT_LOG>
      <match fluent.**>
        @type null
      </match>
    </label>  

    # TCP input to receive logs from the forwarders
    <source>
      @type forward
      bind 0.0.0.0
      port 24224
    </source>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type null
    </match>

    # Send the logs to the standard output
    <match **>
      @type             elasticsearch
      include_tag_key   true
      host              "{{ .Release.Name }}-es-http"
      port              "9200"
      user              "elastic"
      password          {{ ( .Values.env.secret.password | b64dec ) | indent 4 | trim | quote }}
      logstash_format   true
      scheme            https
      ssl_verify        false
      logstash_prefix   bazi-logstash
      logstash_prefix_separator -
      logstash_dateformat %Y.%m.%d

      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>
    
    <match benq-capital.**>
      @type             elasticsearch
      include_tag_key   true
      host              "{{ .Release.Name }}-es-http"
      port              "9200"
      user              "elastic"
      password          {{ (.Values.env.secret.password | b64dec) | indent 4 | trim | quote }}
      logstash_format   true
      scheme            https
      ssl_verify        false
      logstash_prefix   benqcapital-logstash
      logstash_prefix_separator -
      logstash_dateformat %Y.%m.%d

      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/benq-capital-logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>
