apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-es-elastic-user"
data: 
  elastic: ZWxhc3RpYw==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: password
data: 
{{- range $key, $val := .Values.env.secret}}
  {{ $key }}: {{ $val }}
{{- end }}
---
{{- if .Values.elasticsearch.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.elasticsearch.tls.secret.secretName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "cert/tls.crt" | b64enc }}  
  tls.key: {{ .Files.Get "cert/tls.key" | b64enc }}
{{- end }}
---
{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: snapshot-secret
type: Opaque
data:
  azure.client.default.account: {{ .Values.backup.storageaccountName }}
  azure.client.default.key: {{ .Values.backup.storageaccountKey }}
{{- end }}
