{{- if .Values.backup.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: es-snapshotter
spec:
  {{ include "efk.cronschedule" . }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: es-snapshotter
            image: centos:7
            volumeMounts:
              - name: es-basic-auth
                mountPath: /mnt/elastic/es-basic-auth
            {{- include "efk.selectIndices" . }}
          restartPolicy: OnFailure
          volumes:
          - name: es-basic-auth
            secret:
              secretName: {{ .Release.Name }}-es-elastic-user
{{- end }}
  